### ISSUE TITLE
`JsonLogger` allows exceptions to be raised during serialization

### ISSUE THREAD

**Issue by johnduhart** [JordiPolo/lorekeeper#29]
While attempting to log data that (admittedly) could not be represented in JSON, Lorekeeper bubbled up this exception.

```
"/home/app/web/vendor/bundle/ruby/2.7.0/gems/lorekeeper-2.1.0/lib/lorekeeper/fast_logger.rb:52:in `block (2 levels) in <class:FastLogger>'"
"/home/app/web/vendor/bundle/ruby/2.7.0/gems/lorekeeper-2.1.0/lib/lorekeeper/fast_logger.rb:60:in `add'"
"/home/app/web/vendor/bundle/ruby/2.7.0/gems/lorekeeper-2.1.0/lib/lorekeeper/json_logger.rb:151:in `log_data'"
"/home/app/web/vendor/bundle/ruby/2.7.0/gems/lorekeeper-2.1.0/lib/lorekeeper/json_logger.rb:151:in `dump'"
"JSON::GeneratorError: Infinity not allowed in JSON."
```

Should Lorekeeper be more robust in this case, and attempt to log without custom fields? If all else fails, log the serialization exception.

**Comment by miniengineer** [comment]
A PR https://github.com/JordiPolo/lorekeeper/pull/32 is on the way

**Comment by miniengineer** [comment]
Done 🎉
